tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "neovim"
brew "getantibody/tap/antibody"
brew "git"
brew "go"
brew "exa"
brew "node"
brew "yarn"
brew "diff-so-fancy"

cask "font-fira-code"
cask "iterm2"
cask "karabiner"
